#! /bin/bash
# Copyright ©2022 XSans02
# Just a simple script for auto push aosp-clang

# Function to show an informational message
msg() {
    echo -e "\e[1;32m$*\e[0m"
}

# Installing some deps
apt-get install -y git wget tar git-lfs

# Set a directory
export DIR="$(pwd ...)"

# set a clang version
export CLANG_VERSION="clang-r437112b"  # See latest from https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/master

git config --global http.version HTTP/1.1
git config --global http.postBuffer 524288000
git config --global user.name "$GH_USERNAME"
git config --global user.email "$GH_EMAIL"

mkdir ${DIR}/tmp
cd ${DIR}/tmp

msg "Start Cloning ..."
wget --quiet https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/${CLANG_VERSION}.tgz
tar -xf ${CLANG_VERSION}.tgz
rm -rf ${CLANG_VERSION}.tgz

git clone "https://$GH_USERNAME:$GH_TOKEN@$GH_PUSH_REPO_URL" ${DIR}/push
rm -rf ${DIR}/push/*
cp -rf ${DIR}/tmp/* ${DIR}/push/

cd ${DIR}/push/
git add .
git commit -s --quiet -m "Import AOSP Clang from https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/${CLANG_VERSION}"
git lfs migrate import --include="*git"
git push origin
